@startuml
hide empty description
state "choice1" <<choice>>
state "choice2" <<choice>>


[*] --> Neutral
Neutral -> Neutral: Mouse Wheel
Neutral --> DragChart: Mouse Down
Neutral --> choice1: Mouse Move

DragChart --> DragChart: Mouse Move
DragChart --> Neutral: Mouse Up

choice1 --> choice2: Drawing Mode\n and Hovering drawing?
choice1 --> Neutral: Not in Drawing Mode\nor not hovering drawing

choice2 --> HoverHandle: Hovering Handle?
choice2 --> HoverDrawing: Not Hovering Handle

HoverDrawing --> choice1: Mouse Move
HoverDrawing --> DragDrawing: Mouse Down

DragDrawing --> DragDrawing: Mouse Move
DragDrawing --> choice1: Mouse Up

HoverHandle --> choice1: Mouse Move
HoverHandle --> DragHandle: Mouse Down

DragHandle --> DragHandle: Mouse Move
DragHandle --> choice1: Mouse Up

@enduml
